MM_AO		/* Memory address offset */
ABL_AO		/* Address block address offset */
CPO_AO		/* Component address offset */

FLD_BOL		/* Field bit offset lower */
FLD_BOU		/* Field bit offset upper */
FLD_BW		/* Field bit width */


#typedef enum{
	COMPONENTNAME_READWRITE
	COMPONENTNAME_READONLY
	COMPONENTNAME_WRITEONLY
	COMPONENTNAME_

}SPIRIT_ACCESSTYPE_T

#typedef enum{

} SPIRIT_USAGETYPE_T


#define ADDRESSBLOCKNAME_NAME			'Name'
#define ADDRESSBLOCKNAME_USAGE			SPIRIT_USAGETYPE_T
#define ADDRESSBLOCKNAME_BASEADDRESS		0x00000000
#define ADDRESSBLOCKNAME_RANGE			128		
#define ADDRESSBLOCKNAME_WIDTH			32
#define ADDRESSBLOCKNAME_DESCRIPTION		'String'
#define ADDRESSBLOCKNAME_ACCESS			SPIRIT_ACCESSTYPE_T
#define ADDRESSBLOCKNAME_VOLATILE		False



/* Register*/
#define ADDRESSBLOCKNAME_REGISTERNAME_NAME		'None'
#define ADDRESSBLOCKNAME_REGISTERNAME_SIZE		128
#define ADDRESSBLOCKNAME_REGISTERNAME_DIMENSION		1
#define ADDRESSBLOCKNAME_REGISTERNAME_DESCRIPTION	'Test'
#define ADDRESSBLOCKNAME_REGISTERNAME_VOLATILE		false
#define ADDRESSBLOCKNAME_REGISTERNAME_ACCESS		SPIRIT_ACCESSTYPE_T
#define ADDRESSBLOCKNAME_REGISTERNAME_RESETVALUE	0xDEADBEEF
#define ADDRESSBLOCKNAME_REGISTERNAME_RESETMASK		0xDEADBEEF
#define ADDRESSBLOCKNAME_REGISTERNAME_OFFSETAUB		0xDEADBEEF 	/* Offset to address block baseaddress */
#define ADDRESSBLOCKNAME_REGISTERNAME_OFFSETCMP		0x80080000	/* Offset to component baseaddress */


/* Field */
#define ADDRESSBLOCKNAME_REGISTERNAME_FIELDNAME_NAME			'None'
#define ADDRESSBLOCKNAME_REGISTERNAME_FIELDNAME_DESCRIPTION		'Some field' 
#define ADDRESSBLOCKNAME_REGISTERNAME_FIELDNAME_OFFSETBITS		0x00
#define ADDRESSBLOCKNAME_REGISTERNAME_FIELDNAME_WIDTHBITS		0x00
#define ADDRESSBLOCKNAME_REGISTERNAME_FIELDNAME_VOLATILE		'false'
#define ADDRESSBLOCKNAME_REGISTERNAME_FIELDNAME_ACCESS			AccessEnum
#define ADDRESSBLOCKNAME_REGISTERNAME_FIELDNAME_MODIFIEDWRITEVALUE	ModifiedWriteValueEnum	
#define ADDRESSBLOCKNAME_REGISTERNAME_FIELDNAME_READACTION		ReadActionEnum
#define ADDRESSBLOCKNAME_REGISTERNAME_FIELDNAME_TESTABLE		boolean
#define ADDRESSBLOCKNAME_REGISTERNAME_FIELDNAME_TESTCONSTRAINT		TestConstraintEnum



